# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [2]:
### [your code here]
print("NumPy version:", np.__version__)
np.show_config()


NumPy version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.21
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep4347739648
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong, -O2, -pipe, -isystem,
      /opt/anaconda3/include, -fdebug-prefix-map=/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_a51i_mbs7m/croot/numpy_and_numpy_base_1708638620867/work=/usr/local/src/conda/numpy-base-1.26.4,
      -fdebug-prefix-map=/opt/anac

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [4]:
### [your code here]
a = np.random.rand(2, 3, 5)


### 4. Print a.


In [5]:
### [your code here]
print(a)

[[[0.06741216 0.65156069 0.49948377 0.67629799 0.91217073]
  [0.74486047 0.18855902 0.8400082  0.87358415 0.11124681]
  [0.62973715 0.48366355 0.91678148 0.49918963 0.34441255]]

 [[0.410385   0.55717773 0.40581528 0.49032141 0.16961717]
  [0.19171054 0.43257288 0.20416509 0.85513023 0.16278453]
  [0.97466245 0.37085047 0.27925225 0.86990384 0.08682808]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [7]:
### [your code here]
b = np.ones((5, 2, 3))


### 6. Print b.


In [8]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [2]:
### [your code here]
import numpy as np
a = np.random.rand(2, 3, 5)
b = np.ones((5, 2, 3))
print(a.size == b.size)


True



### 8. Are you able to add a and b? Why or why not?


In [3]:
### [your code here]
#We can't add them together, they have differnt shapes, we would get an error



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [4]:
### [your code here]
import numpy as np
b = np.ones((5, 2, 3))
c = np.transpose(b,(1,2,0))
print(c.shape)


(2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [5]:
### [your code here]
import numpy as np
a = np.random.rand(2, 3, 5)
b = np.ones((5, 2, 3))
c = np.transpose(b,(1,2,0))
d = a + c
print(d)

[[[1.4029096  1.61025795 1.58797883 1.33866598 1.08911373]
  [1.44615462 1.15095528 1.22998328 1.05121783 1.49848733]
  [1.73379987 1.94557209 1.98654547 1.90310434 1.46904423]]

 [[1.33750971 1.42847239 1.04873656 1.5975999  1.56716503]
  [1.17808203 1.33341597 1.06519301 1.3771095  1.97793893]
  [1.35137008 1.92703598 1.45757055 1.45433872 1.4023273 ]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [7]:
### The value of d is what we have in a but increased by one

import numpy as np
a = np.random.rand(2, 3, 5)
b = np.ones((5, 2, 3))
c = np.transpose(b,(1,2,0))
d = a + c
print(a)
print(d)



[[[0.75206162 0.51310369 0.26138    0.61531539 0.18450971]
  [0.70567908 0.79289179 0.10175929 0.54864521 0.04316921]
  [0.93838883 0.74041156 0.17962398 0.49549223 0.56324801]]

 [[0.56529706 0.18760748 0.59035063 0.38390207 0.82414021]
  [0.86276366 0.52478499 0.54166452 0.68447091 0.74756018]
  [0.25863006 0.82989555 0.88448823 0.92628557 0.56317635]]]
[[[1.75206162 1.51310369 1.26138    1.61531539 1.18450971]
  [1.70567908 1.79289179 1.10175929 1.54864521 1.04316921]
  [1.93838883 1.74041156 1.17962398 1.49549223 1.56324801]]

 [[1.56529706 1.18760748 1.59035063 1.38390207 1.82414021]
  [1.86276366 1.52478499 1.54166452 1.68447091 1.74756018]
  [1.25863006 1.82989555 1.88448823 1.92628557 1.56317635]]]



### 12. Multiply a and c. Assign the result to e.


In [10]:
import numpy as np
a = np.random.rand(2, 3, 5)
b = np.ones((5, 2, 3))
c = np.transpose(b,(1,2,0))
e = a * c
print(e)


[[[0.22316817 0.90784347 0.81681861 0.31905351 0.6416742 ]
  [0.25976627 0.96428699 0.1572502  0.03217979 0.43412398]
  [0.28866783 0.57185607 0.34930197 0.59289398 0.47897274]]

 [[0.7057442  0.11036399 0.86804467 0.50946947 0.00375211]
  [0.46034471 0.84736817 0.32027115 0.10159172 0.5231377 ]
  [0.59549844 0.23318745 0.64217948 0.24561978 0.50764669]]]




### 13. Does e equal to a? Why or why not?


In [ ]:
### e does equal to a because ih has the same dimensions 
import numpy as np
a = np.random.rand(2, 3, 5)
b = np.ones((5, 2, 3))
c = np.transpose(b,(1,2,0))
e = a * c
print(e.size == a.size)



True




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [14]:
### [your code here]
import numpy as np
d_max = np.max
d_min = np.min
d_mean = np.mean
print(d_max)
print(d_min)
print(d_mean)



<function max at 0x11f37d3a0>
<function min at 0x11f37d4e0>
<function mean at 0x11f37dda0>



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [15]:
### [your code here]
import numpy as np
f = np.empty_like(d)
print(f)

[[[0.22316817 0.90784347 0.81681861 0.31905351 0.6416742 ]
  [0.25976627 0.96428699 0.1572502  0.03217979 0.43412398]
  [0.28866783 0.57185607 0.34930197 0.59289398 0.47897274]]

 [[0.7057442  0.11036399 0.86804467 0.50946947 0.00375211]
  [0.46034471 0.84736817 0.32027115 0.10159172 0.5231377 ]
  [0.59549844 0.23318745 0.64217948 0.24561978 0.50764669]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [17]:
### [your code here]
import numpy as np
d_min = np.min(d)
d_mean = np.mean(d)
d_max = np.max(d)
f = np.empty_like(d)
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value = d[i, j, k]
            if value == d_min:
                f[i, j, k] = 0
            elif value == d_max:
                f[i, j, k] = 100
            elif value == d_mean:
                f[i, j, k] = 50
            elif d_min < value < d_mean:
                f[i, j, k] = 25
            elif d_mean < value < d_max:
                f[i, j, k] = 75
print(f)


[[[ 75.  25.  25.  75.  25.]
  [ 75.  75.  25.  25.   0.]
  [100.  75.  25.  25.  75.]]

 [[ 75.  25.  75.  25.  75.]
  [ 75.  25.  25.  75.  75.]
  [ 25.  75.  75.  75.  75.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [18]:
### [your code here]
import numpy as np
print(d)
print(f)

[[[1.75206162 1.51310369 1.26138    1.61531539 1.18450971]
  [1.70567908 1.79289179 1.10175929 1.54864521 1.04316921]
  [1.93838883 1.74041156 1.17962398 1.49549223 1.56324801]]

 [[1.56529706 1.18760748 1.59035063 1.38390207 1.82414021]
  [1.86276366 1.52478499 1.54166452 1.68447091 1.74756018]
  [1.25863006 1.82989555 1.88448823 1.92628557 1.56317635]]]
[[[ 75.  25.  25.  75.  25.]
  [ 75.  75.  25.  25.   0.]
  [100.  75.  25.  25.  75.]]

 [[ 75.  25.  75.  25.  75.]
  [ 75.  25.  25.  75.  75.]
  [ 25.  75.  75.  75.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.